services:
  data-processing:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "9000:8080"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - S3_ENDPOINT_URL=http://localstack:4566/
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
#    volumes:
#      - "./model:/app/model"
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3